### ISSUE TITLE
ImportError: No module named  'consts'

### ISSUE THREAD

**Issue by oden3000** [mcldev/DjangoCMS_Charts#1]
Created a new project within Divio and added only this addon to generate the following message.

Step 7/7 : RUN DJANGO_MODE=build python manage.py collectstatic --noinput
 ---> Running in f75f57df933e
[91m/virtualenv/lib/python3.5/site-packages/storages/__init__.py:9: UserWarning: This library has been designated as the official successor of django-storages and releases under that namespace. Please update your requirements files to point to django-storages.
  warnings.warn('This library has been designated as the official successor of django-storages and '
[0m[91mTraceback (most recent call last):
  File "manage.py", line 7, in <module>
    startup.manage(path=os.path.dirname(os.path.abspath(__file__)))
  File "/virtualenv/lib/python3.5/site-packages/aldryn_django/startup.py", line 11, in manage
[0m[91m    utility.execute()
  File "/virtualenv/lib/python3.5/site-packages/django/core/management/__init__.py", line 328, in execute
[0m[91m    django.setup()
  File "/virtualenv/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/virtualenv/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
[0m[91m    app_config.import_models(all_models)
  File "/virtualenv/lib/python3.5/site-packages/django/apps/config.py", line 198, in import_models
[0m[91m    self.models_module = import_module(models_module_name)
  File "/virtualenv/lib/python3.5/importlib/__init__.py", line 126, in import_module
[0m[91m    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
[0m[91m  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
[0m[91m  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
[0m[91m  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
[0m[91m  File "/virtualenv/lib/python3.5/site-packages/djangocms_charts/models.py", line 4, in <module>
    from .chartjs.models import *
[0m[91m  File "/virtualenv/lib/python3.5/site-packages/djangocms_charts/chartjs/models.py", line 3, in <module>
[0m[91m    from djangocms_charts.base.models import ChartsBaseModel
  File "/virtualenv/lib/python3.5/site-packages/djangocms_charts/base/models.py", line 5, in <module>
    import consts
ImportError: No module named 'consts'
[0m

**Comment by Nurfen** [comment]
I'm having the same issue when using Divio. It should probably be 
`import .consts `
Will this be fixed or is this project dead?
